### PR TITLE
Removes mixed space and tab. Includes the project name to the HTML title.

### PR DESCRIPTION
**Pull request by thedanheller**
I love using this p5 manager. 2 things bother me, though. The broken indentation on the HTML file and the project name not being in the HTML title. I’ve made this quick fixing and implementation. Feel free to ignore them if you think it’s not relevant.

Thanks!

### CODE REVIEW

**Comment by thedanheller** [comment]
also feel free to change the .editorconfig as you like.

**Comment by chiunhau** [comment]
@daniloprates Thank you!!! I didn't notice these details before. ( I'm so surprised that you can understand my dirty code 😃

**Comment by thedanheller** [comment]
Glad you liked it :)

**Comment by chiunhau** [comment]
This fix would be published soon. 
Btw, I'm now working on issue #5. I think that `.p5rc` is not the best way to track projects...but I haven't come up with a alternative yet. Do you have any suggestion?

**Comment by thedanheller** [comment]
What about a json file? So you could have more info about the project, eg

``` json
{
    "projects" : [
        {
            "name": "my project 1",
            "slug": "my-project-1",
            "libs": [
                "https://cdn.rawgit.com/generative-light/p5.scribble.js/master/p5.scribble.js"
            ]
        },
        {
            "name": "my project 2",
            "slug": "my-project-2",
            "libs": []
        }
    ]
}

```

**Pull request merged**
